// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return android;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        return android;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3DClDa5pr9dblpAtNXfRvGU9trr7ZtwI',
    appId: '1:892894654736:android:29f83633c08fcaecf2f595',
    messagingSenderId: '892894654736',
    projectId: 'kapada-creation-dev',
    storageBucket: 'kapada-creation-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3DClDa5pr9dblpAtNXfRvGU9trr7ZtwI',
    appId: '1:892894654736:ios:29f83633c08fcaecf2f595',
    messagingSenderId: '892894654736',
    projectId: 'kapada-creation-dev',
    storageBucket: 'kapada-creation-dev.firebasestorage.app',
    iosBundleId: 'com.kc.kcapp.app',
  );
}
